name: TaskBud
description: A Buddy App to Schedule Your Life.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.3.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Scoped model
  scoped_model: ^1.0.1
  # for http services
  http: ^0.11.3+16
  # for storing key pair value on device
  shared_preferences: ^0.4.3
  # Reactive programming library for dart
  rxdart: ^0.20.0
  # For google maps
  map_view: ^0.0.12
  # for device location
  location: ^1.2.0
  # for gallery access
  image_picker: ^0.4.5
  #for mime
  mime: ^0.9.6
  # DateTime picker
  datetime_picker_formfield: ^0.1.7
  # Url launcher
  url_launcher: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: #000000
  # adaptive_icon_foreground: "assets/icon/icon-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/quote.jpg
  - assets/background.jpg
  - assets/splash_screen.png
  #    - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Oswald
    fonts:
    - asset: assets/font/Oswald-Bold.ttf
      weight: 700
  - family: A-Sensible-Armadillo
    fonts:
    - asset: assets/font/A-Sensible-Armadillo.ttf
      weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
